""" removed pdf column from report table and added prediction column in metric table

Revision ID: 04f6cb3c68f9
Revises: acbcfa023db1
Create Date: 2025-04-03 17:34:03.504410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04f6cb3c68f9'
down_revision = 'acbcfa023db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction', sa.Boolean(), nullable=False))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('pdf_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file', postgresql.BYTEA(), autoincrement=False, nullable=False))

    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_column('prediction')

    # ### end Alembic commands ###
