"""Added age and gender column to the user table.

Revision ID: 2e57e893a083
Revises: c1a4bebfa7f2
Create Date: 2025-04-10 21:42:17.616194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e57e893a083'
down_revision = 'c1a4bebfa7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.Enum('Male', 'Female', name='gender_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
