"""metric table

Revision ID: 517ae349ccfe
Revises: 9656cc918c4b
Create Date: 2025-03-04 23:43:14.205458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517ae349ccfe'
down_revision = '9656cc918c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender_enum'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('current_smoker', sa.Boolean(), nullable=False),
    sa.Column('cigs_per_day', sa.Integer(), nullable=False),
    sa.Column('bp_meds', sa.Boolean(), nullable=False),
    sa.Column('prevalent_stroke', sa.Boolean(), nullable=False),
    sa.Column('prevalent_hyp', sa.Boolean(), nullable=False),
    sa.Column('diabetes', sa.Boolean(), nullable=False),
    sa.Column('cholesterol', sa.Integer(), nullable=False),
    sa.Column('sys_bp', sa.Integer(), nullable=False),
    sa.Column('dia_bp', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Integer(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.Column('glucose', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric')
    # ### end Alembic commands ###
