"""Added height and weight metric in the metric table

Revision ID: 71c086645a1a
Revises: 2e57e893a083
Create Date: 2025-04-20 19:35:01.676811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c086645a1a'
down_revision = '2e57e893a083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
