"""added timestamp to metric table

Revision ID: 75b464911a91
Revises: 2c10c51cb48d
Create Date: 2025-03-31 21:41:25.198881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b464911a91'
down_revision = '2c10c51cb48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.TIMESTAMP(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
