"""minor update in user table

Revision ID: 9656cc918c4b
Revises: ed41d6f29f2f
Create Date: 2025-02-24 00:15:45.156915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9656cc918c4b'
down_revision = 'ed41d6f29f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('user_phone_number_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('phone_number')
        batch_op.drop_column('location')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_phone_number_key', ['phone_number'])
        batch_op.drop_column('username')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
