"""Added pdf file column to report table

Revision ID: acbcfa023db1
Revises: 75b464911a91
Create Date: 2025-04-02 19:50:46.199994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbcfa023db1'
down_revision = '75b464911a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('pdf_file')

    # ### end Alembic commands ###
