"""minor changes to the metric table

Revision ID: c1a4bebfa7f2
Revises: 04f6cb3c68f9
Create Date: 2025-04-03 18:22:12.144698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a4bebfa7f2'
down_revision = '04f6cb3c68f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.alter_column('prediction',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.alter_column('prediction',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
